<?php /** @var $block \ThanhVo\BaiduAnalytics\Block\Ba */ ?>
<!-- BEGIN BAIDU ANALYTICS CODE -->
<script type="text/x-magento-init">
{
    "*": {
        "ThanhVo_BaiduAnalytics/js/baidu-analytics": {
            "isCookieRestrictionModeEnabled": <?= (int)$block->isCookieRestrictionModeEnabled() ?>,
            "currentWebsite": <?= (int)$block->getCurrentWebsiteId() ?>,
            "cookieName": "<?= /* @noEscape */ \Magento\Cookie\Helper\Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
            "pageTrackingData": <?= /* @noEscape */ json_encode($block->getPageTrackingData()) ?>
        }
    }
}
</script>
<!-- END BAIDU ANALYTICS CODE -->
